# Generated by Django 2.2.26 on 2022-01-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contact'),
    ]

    operations = [
    ]
